version: "3"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        depends_on:
            - backend
        stdin_open: true
        networks:
            - react-express
        environment:
            - FAST_REFRESH=${FAST_REFRESH}
            - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
            - REACT_APP_TEST=${REACT_APP_TEST}
            - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
            - URI${URI}
            - JWT_SECRET_KEY${JWT_SECRET_KEY}

    backend:
        build: ./backend
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - react-express
        restart: always
        environment:
            - FAST_REFRESH=${FAST_REFRESH}
            - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
            - REACT_APP_TEST=${REACT_APP_TEST}
            - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
            - URI${URI}
            - JWT_SECRET_KEY${JWT_SECRET_KEY}

networks:
    react-express:
